{"uuid": "b52a0388-dacc-444d-83fa-9901c4382d09", "children": ["b0c221d7-08d8-43ac-ab8d-78be71d9648e"], "befores": [{"name": "with_login_cpc", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"d:\\python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\coding\\case\\conftest.py\", line 10, in with_login_cpc\n    cpclogin = CpCLoginPage(BoxDriver())\n  File \"d:\\coding\\base\\box.py\", line 58, in __init__\n    driver = webdriver.Chrome(chrome_options=profile)\n  File \"d:\\python37-32\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"d:\\python37-32\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1568962985360, "stop": 1568962985362}], "start": 1568962985360, "stop": 1568962985436}